#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then you need to set the SHELL environment variable to point to
#       that shell before running this script, e.g.:
#           SHELL=/bin/bash ./gradlew
#
#       The script will refuse to run if it detects that /bin/sh is noncompliant.
#
#   (2) The script will look for a `gradle` installation in a directory named by the
#       `GRADLE_HOME` environment variable. If it is not found, it will look for a
#       `gradle` executable on the PATH, and finally for a `gradlew` script next to
#       the script itself.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -n is undefined. So we treat it as a no-op.
        # In particular, the check for "unlimited" and setting to a specific value will fail, but we just want to go on.
        # In practice, we want to test if the limit is greater than 0 (for file descriptors), and not hardcode a value.
        ;;
      *)
        if ulimit -n -t 2> /dev/null && [ "$(ulimit -n)" != "unlimited" ] ; then
            if [ "$(ulimit -n)" -lt "$MAX_FD" ] ; then
                warn "Could not set maximum file descriptor limit: $(ulimit -n) < $MAX_FD"
            else
                ulimit -n -s "$MAX_FD" || warn "Could not set maximum file descriptor limit to $MAX_FD"
            fi
        fi
        ;;
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*};              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back at the beginning.
        set -- "$@" "$arg"
    done
fi

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     shell script including quotes and variable substitutions, so put them in
#     double quotes to make sure that they get re-expanded; and
#   * put everything else in single quotes, so that it is not re-expanded.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
# Without this support, Apple's Java 1.6 will only parse space-separated args.
#
# It is safe to use this approach because it will not execute the parsed arguments.
#
# In addition, this approach can handle arguments that contain spaces and
# other special characters.
#
# xargs will read from stdin (the file descriptor 3) and will interpret the
# input as if it were quoted arguments.  By using this approach, we can feed
# the arguments to xargs and let it handle the quoting.
#
# (The IFS is set to the empty string so that xargs treats each argument as a
# separate argument, not as a single string with spaces.)
#
# Note that some implementations of xargs (like the BSD one) require that the
# -0 option be used to read null-separated input.  However, we use the -0
# option only as a last resort; if we detect a BSD xargs, we will use the -0
# option.  Also, some implementations of xargs treat the -0 option as a
# no-op, which is fine.
#
# We use the -L 1 option to ensure that xargs reads one line at a time into
# its command.  This is necessary because the Apple 1.6 implementation of
# xargs does not support the -0 option, but it does support the -L option.
#
# In addition, this approach prevents xargs from trying to parse quotes in
# the arguments, which is necessary for arguments that contain spaces.
#
# Note that the trailing newline is removed by the pipe, and that is okay
# because the xargs command will treat the resulting input as if it were one
# argument per line, even if there were blank lines.  This is because the -L
# 1 option will cause xargs to read one line at a time and will treat a blank
# line as an empty argument, which is fine.
#
# Because we use the -L 1 option, we must be careful to ensure that we do not
# pass an empty argument to xargs, as that will cause it to read from stdin
# and then hang (because there is no more input).  To avoid this, we will
# check the number of arguments before passing them to xargs.

if [ $# -eq 0 ]; then
    die "No arguments provided"
fi

# We need to run xargs with the -L 1 option to ensure that it reads one
# argument per line.  We also need to set the IFS to the empty string so that
# xargs will treat each argument as a separate argument, not as a single
# string with spaces.
IFS=
xargs -L 1 -0 </dev/fd/3 2>/dev/null <<-EOF
$(printf '%s\n' "$@")
EOF

# The xargs command will output the command to run on stdout, which we then
# feed back into the shell.
exec /bin/sh <<EOF
$(xargs -L 1 -0 </dev/fd/3 2>/dev/null)
EOF
